services:
  - type: web
    name: coldemail-server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
  - type: static
    name: coldemail-client
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    autoDeploy: true

